package examples;

import net.firstpartners.core.log.IStatusUpdate;

import net.firstpartners.data.Cell;
import net.firstpartners.data.Range;

global IStatusUpdate log;

rule "example 2 log then modify cell values" 

	when
		$cell : Cell(modified==false)
       
    then
        	   
    	//Note: use the 'modify' block instead 
    	//want to give the rule engine a chance to react to these changes
    	$cell.setModified(true);
    	
    	 //Logging message
    	log.addUIInfoMessage("initial cell value:"+$cell);
    	
end
