package net.firstpartners.sample.ExcelDataRules;

import net.firstpartners.core.log.IStatusUpdate;

import net.firstpartners.data.Cell;
import net.firstpartners.data.Range;

//Red Piranha gives us a logging object
global IStatusUpdate log;
	
rule "print cell initial values" 

	when
		$cell : Cell(value=="hello")
       
    then
        	   
        //Logging message
    	log.addUIInfoMessage("The Rule Engine says back - Hello World!");
    	
    	
end



rule "print cell modified values" 


	when
		$cell : Cell(modified==true)
       
    then
        	   
        //Logging message
    	log.addUIInfoMessage("modified cell value:"+$cell);
    	
    	
end


/*
#This rule is commented out - prints *lots* of information on our ranges if enabled

rule "print range" 


	when
		$range : Range()
       
    then
        	   
        //Logging message
    	log.addUIInfoMessage("rule:"+$range.toShortString());

end*/
