package sample.catalogue;

import net.firstpartners.core.log.ILogger
import net.firstpartners.data.Cell;

global ILogger log;


rule "test following cell"

	when 
		$cellFind : Cell( value == "Turnover") 	$nextCell : Cell (name== $cellFind.nextName) $cell : Cell (name== $nextCell.nextName)
	then 
	    log.info("Logging YYY "+$nextCell2.getValue());
	    $nextCell2.setName("Turnover");
end

rule "log then modify cell values" 

	when
		$cell : Cell( name == "PARA_6_CUSTOMER No.")
       
       
    then
        	   
    	//Note: use the 'modify' block instead 
    	//want to give the rule engine a chance to react to these changes
    	//$cell.setModified(true);
    	//$cell.setOriginalTableReference("UPDATE - should not fire");
    	//$cell.setName("Company (Application) Address_2");
   	   	
    	 //Logging message
    	log.info("!!!Updating  Name to flag on cell value:"+$cell);	
    	
end

/**
scratchpad where we keep a sample of the rules -run tests later against here

*/
rule "insert cell to capture warnings" 
	no-loop
	when
			$cell : Cell( name == "PARA_6_CUSTOMER No.:",value !="XX CRO No.:")
    then   
    	 //Logging message
    	log.info("Updating warning flag on "+$cell);
    	modify($cell) {setComment("WARNING cellName:"+$cell.getName()+" has unexpected value of "+$cell.getValue())};	
end


rule "Collate warnings" 

	when
			$cell : Cell( comment!=null)
    then   
    	 //Logging message
    	log.info("cell with comments:"+$cell);
end


rule "log then modify cell values" 

	when
		$cell : Cell( name == "PARA_6_CRO No.")
       
       
    then
        	   
    	//Note: use the 'modify' block instead 
    	//want to give the rule engine a chance to react to these changes
    	//$cell.setModified(true);
    	//$cell.setOriginalTableReference("UPDATE - should not fire");
    	//$cell.setName("Company (Application) Address_2");
   	   	
    	 //Logging message
    	log.info("!!!Updating  Name to flag on cell value:"+$cell);	
    	
end


rule "sample of rule warnings cell to capture warnings" 
	no-loop
	when
			$cell : Cell( name == "PARA_6_CRO No.:",value !="XX CRO No.:")
    then   
    	 //Logging message
    	log.info("Updating warning flag on "+$cell);
    	modify($cell) {setComment("WARNING cellName:"+$cell.getName()+" has unexpected value of "+$cell.getValue())};	
end



rule "insert cell to capture warnings" 
	no-loop
	when
		not Cell( name == "Validation Notes")
    then   
    	 //Logging message
    	log.info("inserting cell to gather validation notes");
    	insert(new Cell("Validation Notes",""));
end

rule "check valiation notes" 
	no-loop
	when
		$cell : Cell( name == "Validation Notes")
    then   
    	 //Logging message
    	log.info("Validation notes:"+$cell.getValue());
   
end


rule "Collate warnings" 
    no-loop
	when
			$cell : Cell( comment!=null)
			$validation :  Cell( name == "Validation Notes")
    then   
    	 //Logging message
    	log.info("noted cell:"+$cell+" with comments:"+$cell.getComment());
    	modify($validation) {appendValue("\n"+$cell.getComment())};
    	
end