package net.firstpartners.sample.ExcelDataRules;



import net.firstpartners.core.log.IStatusUpdate;

import net.firstpartners.data.Cell;
import net.firstpartners.data.Range;

global IStatusUpdate log;



rule "print cell initial values" 


	when
		$cell : Cell(modified==false)
       
    then
        	   
        //Logging message
    	log.info("initial cell value:"+$cell);
    	
    	
end



rule "print cell modified values" 


	when
		$cell : Cell(modified==true)
       
    then
        	   
        //Logging message
    	log.info("modified cell value:"+$cell);
    	
    	
end


/*
#This rule is commented out - prints *lots* of information on our ranges if enabled

rule "print range" 


	when
		$range : Range()
       
    then
        	   
        //Logging message
    	log.info("rule:"+$range.toShortString());

end*/
