# What this file is
# how to run - from within this directory (-d gives logging messages from server)
#     docker-compose up -d
#
# How to Stop 
#     from this directory: docker-compose down
#     Open in Docker Desktop, stop there


version: '2.3.1'
services:

# Sample applications Provided by RedHat Jboss
# This image contains both Business Central Editor and KIE Server for execution
  business-central :
    container_name: Business-Central-and-KIE-Server     
    # image: jboss/jbpm-server-full:latest                              #older version , hosted on docker
    # image: quay.io/kiegroup/business-central-workbench-showcase:latest       #latest version, hosted on Red Hat Quay - showcase variant gives users setup
    image: quay.io/kiegroup/business-central-workbench-showcase:7.73.0.Final # Specific version, so new updates don't break the book

    ports:
      - 8080:8080
      - 8001:8001
#    volumes:
#      - jbossroot:/opt/jboss/wildfly/                     #everything interesting happens under here


# Docker based application to map from Excel to Jboss tools
# This image generated by Maven from this project (pom.xml in \code folder)
#        mvn spring-boot:build-image -Dmaven.test.skip=true
  


  red:
    #image: paulbrowne/redpiranha:latest                    # if we just want to make sure we get the latest
    image: paulbrowne/redpiranha:2.3.1-SNAPSHOT
    
    ports:
      - 7000:7000
    volumes:
      - redexamples:/workspace/BOOT-INF/classes/examples

    depends_on:
      - business-central

# the names we can find in windows explorer under \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes
volumes:
  redexamples: {}
#  jbossroot: {}



