package net.firstpartners.sample.ExcelDataRules;

import net.firstpartners.core.log.ILogger

import net.firstpartners.data.Cell;

global ILogger log;

rule "log then modify cell values" 

	when
		$cell : Cell(modified==false)
       
    then
        	   
    	//Note: use the 'modify' block instead 
    	//want to give the rule engine a chance to react to these changes
    	$cell.setModified(true);
    	
    	 //Logging message
    	log.info("initial cell value:"+$cell);	
    	
end
	